services:
  gateway:
    image: ${REGISTRY}/rtn-tests-gateway:${IMAGE_TAG}
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/html:/var/www/html:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend-node
      - api

  frontend-node:
    image: ${REGISTRY}/rtn-tests-frontend-node:${IMAGE_TAG}
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=https://api.${API_SITE_NAME}
      - INTERNAL_BACKEND_URL=http://api
      - PORT=3000
    expose:
      - "3000"
    depends_on:
      - api

  api:
    image: ${REGISTRY}/rtn-tests-api:${IMAGE_TAG}
    restart: always
    depends_on:
      - api-php-fpm

  api-php-fpm:
    image: ${REGISTRY}/rtn-tests-api-php-fpm:${IMAGE_TAG}
    restart: always
    environment:
      APP_DEBUG: 0
      SITE_URL: ${API_SITE_URL}
      SITE_NAME: ${API_SITE_NAME}
      DB_HOST: api-postgres
      DB_USER: app
      DB_PASSWORD: ${API_DB_PASSWORD}
      DB_NAME: app
      MAILER_HOST: ${API_MAILER_HOST}
      MAILER_PORT: ${API_MAILER_PORT}
      MAILER_USER: ${API_MAILER_USER}
      MAILER_PASSWORD: ${API_MAILER_PASSWORD}
      MAILER_ENCRYPTION: tls
      MAILER_FROM_EMAIL: ${API_MAILER_FROM_EMAIL}
      MAILER_FROM_NAME: admin
      FRONTEND_URL: http://localhost:8000
      MESSENGER_TRANSPORT_DSN: doctrine://default?auto_setup=0
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      SENTRY_DSN: ${SENTRY_DSN}

  api-php-cli:
    image: ${REGISTRY}/rtn-tests-api-php-cli:${IMAGE_TAG}
    environment:
      APP_DEBUG: 0
      SITE_URL: ${API_SITE_URL}
      SITE_NAME: ${API_SITE_NAME}
      DB_HOST: api-postgres
      DB_USER: app
      DB_PASSWORD: ${API_DB_PASSWORD}
      DB_NAME: app
      MAILER_HOST: ${API_MAILER_HOST}
      MAILER_PORT: ${API_MAILER_PORT}
      MAILER_USER: ${API_MAILER_USER}
      MAILER_PASSWORD: ${API_MAILER_PASSWORD}
      MAILER_ENCRYPTION: tls
      MAILER_FROM_EMAIL: ${API_MAILER_FROM_EMAIL}
      MAILER_FROM_NAME: admin
      FRONTEND_URL: http://localhost:8000
      MESSENGER_TRANSPORT_DSN: doctrine://default?auto_setup=0
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      SENTRY_DSN: ${SENTRY_DSN}

  api-postgres:
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: ${API_DB_PASSWORD}
      POSTGRES_DB: app
    volumes:
      - api-postgres:/var/lib/postgresql/data

volumes:
  api-postgres: