services:
  gateway:
    build:
      context: gateway/docker
      dockerfile: development/nginx/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    depends_on:
      - frontend
      - api
      - mailer

  frontend:
    build:
      context: frontend/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./frontend:/app


  frontend-node-cli:
    build:
      context: frontend/docker/development/node
    volumes:
      - ./frontend:/app


  api:
    build:
      context: api/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./api:/app
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: api/docker
      dockerfile: development/php-fpm/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      APP_DEBUG: 1
      PHP_IDE_CONFIG: serverName=API
      SITE_URL: localhost
      SITE_NAME: Docker
      DB_HOST: api-postgres
      DB_USER: app
      DB_PASSWORD: secret
      DB_NAME: app
      MAILER_HOST: mailer
      MAILER_PORT: 1025
      MAILER_USER: app
      MAILER_PASSWORD: secret
      MAILER_ENCRYPTION: tcp
      MAILER_FROM_EMAIL: admin@site.ru
      MAILER_FROM_NAME: admin
      FRONTEND_URL: http://localhost:8000
      MESSENGER_TRANSPORT_DSN: doctrine://default?auto_setup=0
      TELEGRAM_BOT_TOKEN: 8114548384:AAEiVHE1whxgUCXT_-slDjku0SJXi3_iv5s
      TELEGRAM_CHAT_ID: 1954013093
      SENTRY_DSN: https://4c7ee997911a9ecfa772d8b6aa4e0a92@o4511418890452992.ingest.de.sentry.io/4511419447246928
    volumes:
      - ./api:/app
    depends_on:
      - api-postgres

  api-php-cli:
    build:
      context: api/docker
      dockerfile: development/php-cli/Dockerfile
    volumes:
      - ./api:/app
    environment:
      APP_DEBUG: 1
      SITE_URL: localhost
      SITE_NAME: Docker
      DB_HOST: api-postgres
      DB_USER: app
      DB_PASSWORD: secret
      DB_NAME: app
      MAILER_HOST: mailer
      MAILER_PORT: 1025
      MAILER_USER: app
      MAILER_PASSWORD: secret
      MAILER_ENCRYPTION: tcp
      MAILER_FROM_EMAIL: admin@site.ru
      MAILER_FROM_NAME: admin
      FRONTEND_URL: http://localhost:8000
      MESSENGER_TRANSPORT_DSN: doctrine://default?auto_setup=0
      TELEGRAM_BOT_TOKEN: 8114548384:AAEiVHE1whxgUCXT_-slDjku0SJXi3_iv5s
      TELEGRAM_CHAT_ID: 1954013093
      SENTRY_DSN: https://4c7ee997911a9ecfa772d8b6aa4e0a92@o4511418890452992.ingest.de.sentry.io/4511419447246928

  api-postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    volumes:
      - api-postgres:/var/lib/postgresql
    ports:
      - "54321:5432"

  mailer:
    image: mailhog/mailhog

volumes:
  api-postgres: