# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    oauth.scopes:
        - 'common'

    oauth.clients:
        - name: "rtn-tests"
          client_id: 'frontend'
          secret: 'my-super-secret-123'
          redirect_uri: '%env(FRONTEND_URL)%/oauth'
          grant_types:
              - 'password'
              - 'refresh_token'
              - 'social'


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    League\OAuth2\Server\Repositories\UserRepositoryInterface: '@App\OAuth\Entity\UserRepository'
    League\OAuth2\Server\Repositories\AccessTokenRepositoryInterface: '@App\OAuth\Entity\AccessTokenRepository'
    League\OAuth2\Server\Repositories\AuthCodeRepositoryInterface: '@App\OAuth\Entity\AuthCodeRepository'
    League\OAuth2\Server\Repositories\RefreshTokenRepositoryInterface: '@App\OAuth\Entity\RefreshTokenRepository'

    League\OAuth2\Server\Repositories\ScopeRepositoryInterface:
        factory: [ 'App\Infrastructure\OAuth\Factory\OAuthRepositoryFactory', 'createScopeRepository' ]
        arguments:
            $scopes: '%oauth.scopes%'

    League\OAuth2\Server\Repositories\ClientRepositoryInterface:
        factory: [ 'App\Infrastructure\OAuth\Factory\OAuthRepositoryFactory', 'createClientRepository' ]
        arguments:
            $clients: '%oauth.clients%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'


    App\Auth\Fixture\:
        resource: '../src/Auth/Fixture/'
        tags: [ 'doctrine.fixture.orm' ]
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Frontend\:
        resource: '../src/Frontend'
        tags: ['twig.extension']

    App\Frontend\FrontendUrlGenerator:
        arguments:
            $baseUrl: '%env(resolve:FRONTEND_URL)%'

    App\Auth\Service\Tokenizer:
        arguments:
            $interval: 'PT1H'

    App\Infrastructure\Social\YandexClient:
        arguments:
            $clientId: '%env(YANDEX_CLIENT_ID)%'
            $clientSecret: '%env(YANDEX_CLIENT_SECRET)%'

    App\Infrastructure\Social\GoogleClient:
        arguments:
            $clientId: '%env(GOOGLE_CLIENT_ID)%'
            $clientSecret: '%env(GOOGLE_CLIENT_SECRET)%'

    App\Infrastructure\Social\Registry\ClientRegistry:
        arguments:
            $clients: ['@App\Infrastructure\Social\GoogleClient', '@App\Infrastructure\Social\YandexClient']
